/**
 * PQC adapter modules generated by the Code Refactoring Agent alongside patches.
 * Each adapter exposes the same liboqs-style interface per language:
 *   JavaScript/TypeScript – node:crypto native ML-KEM / ML-DSA (Node.js >= 24.7, OpenSSL 3.5)
 *   Python               – liboqs-python (Open Quantum Safe) + pycryptodome AES-GCM
 *   Go                   – liboqs-go for ML-DSA, Go 1.24 crypto/mlkem for ML-KEM
 *   Java                 – Bouncy Castle 1.80 (FIPS 203/204 ML-KEM / ML-DSA)
 */

export function jsAdapter({ esm = false, typescript = false } = {}) {
  const header = `${typescript ? '// @ts-nocheck\n' : ''}/**
 * QuantumShift PQC adapter — generated by the Code Refactoring Agent (IBM Bob-inspired Code Mode).
 *
 * Uses the native ML-KEM (FIPS 203) and ML-DSA (FIPS 204) implementations in
 * node:crypto (Node.js >= 24.7 / OpenSSL 3.5). A liboqs binding can be swapped in
 * behind this interface without touching call sites.
 */
`;
  const imports = esm ? `import crypto from 'crypto';\nimport fs from 'fs';\n` : `'use strict';\n\nconst crypto = require('crypto');\nconst fs = require('fs');\n`;
  const body = `
const KDF_INFO = Buffer.from('quantumshift-kem-dem-v1');
const deriveKey = (secret) => Buffer.from(crypto.hkdfSync('sha256', secret, Buffer.alloc(0), KDF_INFO, 32));

/** Generates an ML-KEM or ML-DSA key pair ('ml-kem-768' | 'ml-dsa-65'). */
function generateKeyPair(algorithm = 'ml-dsa-65') {
  return crypto.generateKeyPairSync(algorithm);
}

/** ML-DSA-65 signature (replaces RSA-SHA256 / ECDSA). */
function mlDsaSign(data, privateKey, encoding) {
  const sig = crypto.sign(null, Buffer.from(data), privateKey);
  return encoding ? sig.toString(encoding) : sig;
}

function mlDsaVerify(data, publicKey, signature, encoding = 'base64') {
  const sig = Buffer.isBuffer(signature) ? signature : Buffer.from(signature, encoding);
  return crypto.verify(null, Buffer.from(data), publicKey, sig);
}

/** ML-KEM-768 + AES-256-GCM sealing (replaces RSA-OAEP key transport). */
function kemSeal(publicKey, plaintext) {
  const { sharedKey, ciphertext } = crypto.encapsulate(publicKey);
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', deriveKey(sharedKey), iv);
  const data = Buffer.concat([cipher.update(Buffer.from(plaintext)), cipher.final()]);
  const len = Buffer.alloc(2);
  len.writeUInt16BE(ciphertext.length);
  return Buffer.concat([len, ciphertext, iv, cipher.getAuthTag(), data]);
}

function kemOpen(privateKey, sealed) {
  const buf = Buffer.from(sealed);
  const n = buf.readUInt16BE(0);
  const kemCt = buf.subarray(2, 2 + n);
  const iv = buf.subarray(2 + n, 14 + n);
  const tag = buf.subarray(14 + n, 30 + n);
  const decipher = crypto.createDecipheriv('aes-256-gcm', deriveKey(crypto.decapsulate(privateKey, kemCt)), iv);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(buf.subarray(30 + n)), decipher.final()]);
}

/**
 * Hybrid X25519 + ML-KEM-768 key exchange (X25519MLKEM768 construction).
 * Initiator: generateKeys() → send; computeSecret(responderMessage).
 * Responder: respond(initiatorPublic) → { message, secret }.
 */
function createHybridKeyExchange() {
  const x = crypto.generateKeyPairSync('x25519');
  const k = crypto.generateKeyPairSync('ml-kem-768');
  const der = (key) => key.export({ format: 'der', type: 'spki' }).toString('base64');
  const pub = (b64) => crypto.createPublicKey({ key: Buffer.from(b64, 'base64'), format: 'der', type: 'spki' });
  const combine = (ecdh, kem) => deriveKey(Buffer.concat([kem, ecdh]));
  return {
    generateKeys(encoding = 'base64') {
      return Buffer.from(JSON.stringify({ x25519: der(x.publicKey), mlkem: der(k.publicKey) })).toString(encoding);
    },
    respond(peerPublic, encoding = 'base64') {
      const peer = JSON.parse(Buffer.from(peerPublic, encoding).toString());
      const ecdh = crypto.diffieHellman({ privateKey: x.privateKey, publicKey: pub(peer.x25519) });
      const { sharedKey, ciphertext } = crypto.encapsulate(pub(peer.mlkem));
      const message = Buffer.from(JSON.stringify({ x25519: der(x.publicKey), ct: ciphertext.toString('base64') })).toString(encoding);
      return { message, secret: combine(ecdh, sharedKey).toString(encoding) };
    },
    computeSecret(peerMessage, encoding = 'base64') {
      const msg = JSON.parse(Buffer.from(peerMessage, encoding).toString());
      const ecdh = crypto.diffieHellman({ privateKey: x.privateKey, publicKey: pub(msg.x25519) });
      const kem = crypto.decapsulate(k.privateKey, Buffer.from(msg.ct, 'base64'));
      return combine(ecdh, kem).toString(encoding);
    },
  };
}

const b64u = (b) => Buffer.from(b).toString('base64url');
const ttl = (v) => (typeof v === 'number' ? v : Number(String(v).replace(/m$/, '')) * (String(v).endsWith('m') ? 60 : 1));

/** Compact JWS signed with ML-DSA-65 (alg per IETF draft-ietf-cose-dilithium). */
function signJwt(claims, privateKey, { expiresIn, issuer } = {}) {
  const now = Math.floor(Date.now() / 1000);
  const payload = { iat: now, ...claims, ...(expiresIn ? { exp: now + ttl(expiresIn) } : {}), ...(issuer ? { iss: issuer } : {}) };
  const input = \`\${b64u(JSON.stringify({ alg: 'ML-DSA-65', typ: 'JWT' }))}.\${b64u(JSON.stringify(payload))}\`;
  return \`\${input}.\${b64u(crypto.sign(null, Buffer.from(input), privateKey))}\`;
}

function verifyJwt(token, publicKey) {
  const [h, p, s] = String(token).split('.');
  if (!crypto.verify(null, Buffer.from(\`\${h}.\${p}\`), publicKey, Buffer.from(s, 'base64url'))) throw new Error('invalid ML-DSA signature');
  const claims = JSON.parse(Buffer.from(p, 'base64url').toString());
  if (claims.exp && claims.exp < Math.floor(Date.now() / 1000)) throw new Error('token expired');
  return claims;
}

/** Loads a key from a secrets-manager / HSM-mounted file referenced by <NAME>_FILE. */
function loadManagedKey(name) {
  const ref = process.env[\`\${name}_FILE\`];
  if (!ref) {
    console.warn(\`[pqc] \${name}_FILE is not configured — key unavailable\`);
    return null;
  }
  return crypto.createPrivateKey(fs.readFileSync(ref));
}
`;
  const exportsList = 'generateKeyPair, mlDsaSign, mlDsaVerify, kemSeal, kemOpen, createHybridKeyExchange, signJwt, verifyJwt, loadManagedKey';
  const footer = esm ? `\nexport { ${exportsList} };\n` : `\nmodule.exports = { ${exportsList} };\n`;
  return header + imports + body + footer;
}

export function pythonAdapter() {
  return `"""QuantumShift PQC adapter — generated by the Code Refactoring Agent.

Requires liboqs-python (Open Quantum Safe, >= 0.10) and pycryptodome.
ML-KEM-768 (FIPS 203) for key encapsulation, ML-DSA-65 (FIPS 204) for signatures.
"""
import base64
import json
import time

import oqs
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto.Protocol.KDF import HKDF

KEM_ALG = "ML-KEM-768"
SIG_ALG = "ML-DSA-65"
_INFO = b"quantumshift-kem-dem-v1"


class KemPublicKey:
    def __init__(self, raw):
        self.raw = raw


class KemKeyPair:
    """Drop-in replacement for an RSA private key used for key transport."""

    def __init__(self):
        self._kem = oqs.KeyEncapsulation(KEM_ALG)
        self._public = KemPublicKey(self._kem.generate_keypair())

    def public_key(self):
        return self._public

    def decapsulate(self, ciphertext):
        return self._kem.decap_secret(ciphertext)


def generate_kem_keypair():
    return KemKeyPair()


def kem_seal(public_key, plaintext):
    with oqs.KeyEncapsulation(KEM_ALG) as kem:
        ciphertext, shared = kem.encap_secret(public_key.raw)
    key = HKDF(shared, 32, b"", SHA256, context=_INFO)
    cipher = AES.new(key, AES.MODE_GCM)
    data, tag = cipher.encrypt_and_digest(plaintext)
    return len(ciphertext).to_bytes(2, "big") + ciphertext + cipher.nonce + tag + data


def kem_open(keypair, sealed):
    n = int.from_bytes(sealed[:2], "big")
    ct, nonce, tag, data = sealed[2:2 + n], sealed[2 + n:18 + n], sealed[18 + n:34 + n], sealed[34 + n:]
    key = HKDF(keypair.decapsulate(ct), 32, b"", SHA256, context=_INFO)
    return AES.new(key, AES.MODE_GCM, nonce=nonce).decrypt_and_verify(data, tag)


class SigningKey:
    """ML-DSA-65 signing key (replaces EC / RSA signing keys)."""

    def __init__(self):
        self._sig = oqs.Signature(SIG_ALG)
        self.public_key_bytes = self._sig.generate_keypair()

    def sign(self, message):
        return self._sig.sign(message)


def generate_signing_keypair():
    return SigningKey()


def verify(message, signature, public_key_bytes):
    with oqs.Signature(SIG_ALG) as verifier:
        return verifier.verify(message, signature, public_key_bytes)


def _b64u(raw):
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def sign_jwt(claims, signing_key, expires_in=900):
    """Compact JWS with alg ML-DSA-65 (IETF draft-ietf-cose-dilithium)."""
    now = int(time.time())
    payload = {"iat": now, "exp": now + expires_in, **claims}
    signing_input = f"{_b64u(json.dumps({'alg': SIG_ALG, 'typ': 'JWT'}).encode())}.{_b64u(json.dumps(payload).encode())}"
    return f"{signing_input}.{_b64u(signing_key.sign(signing_input.encode()))}"
`;
}

export function goAdapter() {
  return `// Package pqc is the QuantumShift PQC adapter — generated by the Code Refactoring Agent.
//
// Signatures: ML-DSA-65 (FIPS 204) via liboqs-go (Open Quantum Safe).
// Key encapsulation: ML-KEM-768 (FIPS 203) via the Go 1.24 standard library crypto/mlkem.
package pqc

import (
	"crypto/mlkem"

	"github.com/open-quantum-safe/liboqs-go/oqs"
)

// SigAlg is the NIST post-quantum signature algorithm used across the portal.
const SigAlg = "ML-DSA-65"

// SigningKey wraps an ML-DSA-65 key pair managed by liboqs.
type SigningKey struct {
	signer    *oqs.Signature
	PublicKey []byte
}

// GenerateMLDSA65 creates a new ML-DSA-65 signing key.
func GenerateMLDSA65() (*SigningKey, error) {
	s := &oqs.Signature{}
	if err := s.Init(SigAlg, nil); err != nil {
		return nil, err
	}
	pub, err := s.GenerateKeyPair()
	if err != nil {
		s.Clean()
		return nil, err
	}
	return &SigningKey{signer: s, PublicKey: pub}, nil
}

// Sign produces an ML-DSA-65 signature over msg.
func Sign(k *SigningKey, msg []byte) ([]byte, error) {
	return k.signer.Sign(msg)
}

// Verify checks an ML-DSA-65 signature.
func Verify(pub, msg, sig []byte) (bool, error) {
	v := oqs.Signature{}
	defer v.Clean()
	if err := v.Init(SigAlg, nil); err != nil {
		return false, err
	}
	return v.Verify(msg, sig, pub)
}

// GenerateMLKEM768 creates an ML-KEM-768 decapsulation key (standard library).
func GenerateMLKEM768() (*mlkem.DecapsulationKey768, error) {
	return mlkem.GenerateKey768()
}
`;
}

export function javaAdapter(pkg) {
  return `package ${pkg};

import java.nio.ByteBuffer;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Security;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import org.bouncycastle.jcajce.SecretKeyWithEncapsulation;
import org.bouncycastle.jcajce.spec.KEMExtractSpec;
import org.bouncycastle.jcajce.spec.KEMGenerateSpec;
import org.bouncycastle.jcajce.spec.MLDSAParameterSpec;
import org.bouncycastle.jcajce.spec.MLKEMParameterSpec;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

/**
 * QuantumShift PQC adapter — generated by the Code Refactoring Agent.
 * Requires org.bouncycastle:bcprov-jdk18on:1.80 (FIPS 203 ML-KEM / FIPS 204 ML-DSA).
 */
public final class PqcAdapter {

    private static final SecureRandom RANDOM = new SecureRandom();

    static {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            Security.addProvider(new BouncyCastleProvider());
        }
    }

    private PqcAdapter() {}

    /** Provider name; calling this guarantees the provider is registered. */
    public static String provider() {
        return BouncyCastleProvider.PROVIDER_NAME;
    }

    public static KeyPair generateMlKem768() throws GeneralSecurityException {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("ML-KEM", provider());
        kpg.initialize(MLKEMParameterSpec.ml_kem_768, RANDOM);
        return kpg.generateKeyPair();
    }

    public static KeyPair generateMlDsa65() throws GeneralSecurityException {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("ML-DSA", provider());
        kpg.initialize(MLDSAParameterSpec.ml_dsa_65, RANDOM);
        return kpg.generateKeyPair();
    }

    /** ML-KEM-768 encapsulation + AES-256-GCM (replaces RSA key wrapping). */
    public static byte[] kemSeal(PublicKey publicKey, byte[] plaintext) throws GeneralSecurityException {
        KeyGenerator kg = KeyGenerator.getInstance("ML-KEM", provider());
        kg.init(new KEMGenerateSpec(publicKey, "AES"), RANDOM);
        SecretKeyWithEncapsulation secret = (SecretKeyWithEncapsulation) kg.generateKey();
        byte[] encapsulation = secret.getEncapsulation();
        byte[] iv = new byte[12];
        RANDOM.nextBytes(iv);
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(secret.getEncoded(), "AES"), new GCMParameterSpec(128, iv));
        byte[] body = cipher.doFinal(plaintext);
        return ByteBuffer.allocate(4 + encapsulation.length + iv.length + body.length)
                .putInt(encapsulation.length).put(encapsulation).put(iv).put(body).array();
    }

    public static byte[] kemOpen(PrivateKey privateKey, byte[] sealed) throws GeneralSecurityException {
        ByteBuffer buf = ByteBuffer.wrap(sealed);
        byte[] encapsulation = new byte[buf.getInt()];
        buf.get(encapsulation);
        byte[] iv = new byte[12];
        buf.get(iv);
        byte[] body = new byte[buf.remaining()];
        buf.get(body);
        KeyGenerator kg = KeyGenerator.getInstance("ML-KEM", provider());
        kg.init(new KEMExtractSpec(privateKey, encapsulation, "AES"), RANDOM);
        SecretKeyWithEncapsulation secret = (SecretKeyWithEncapsulation) kg.generateKey();
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(secret.getEncoded(), "AES"), new GCMParameterSpec(128, iv));
        return cipher.doFinal(body);
    }
}
`;
}
